# Generated by Django 3.2.19 on 2023-06-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../girl_climbing_gxt5ti', upload_to='images/'),
        ),
    ]
