# Generated by Django 3.2.20 on 2023-07-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_difficulty_level'),
        ('votes', '0002_auto_20230717_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='rating_type',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='recipes.recipe'),
        ),
    ]
