# Generated by Django 3.2.19 on 2023-06-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='../girl_climbing_gxt5ti', upload_to='images/'),
        ),
    ]
