# Generated by Django 3.2.20 on 2023-07-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Dairy-free', 'Dairy-free'), ('Gluten-free', 'Gluten-free'), ('Healthy Meals', 'Healthy Meals'), ('Quick and Easy', 'Quick and Easy')], max_length=20, null=True),
        ),
    ]
